version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=autosiradig
      - MYSQL_USER=arielito
      - MYSQL_PASSWORD=belleza
      - MYSQL_ROOT_PASSWORD=ahhhhh
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local
